# Generated by Django 3.1.7 on 2021-02-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
    ]
