# Generated by Django 3.1.7 on 2021-02-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20210223_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='fullname',
        ),
    ]
