# Generated by Django 3.1.7 on 2021-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20210223_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block_test_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPaddress', models.TextField(verbose_name='IP地址')),
                ('MACaddress', models.TextField(verbose_name='MAC地址')),
                ('Arrowflag', models.BooleanField(verbose_name='是否安装双箭头')),
                ('Updatetime', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'db_table': 'Address_table',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
